### ISSUE TITLE
Wallet crash at launch on macos Mojave

### ISSUE THREAD

**Issue by arminmacx** [cranepay/cranepay-core#1]
Wallet crash at launch on macOS mojave 10.14.3 with this report :

> Termination Reason:    DYLD, [0x1] Library missing
>
>Application Specific Information:
>dyld: launch, loading dependent libraries
>
>Dyld Error Message:
  >Library not loaded: @loader_path/libboost_system-mt.dylib
  >Referenced from: /Applications/Cranepay-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  >Reason: image not found

**Comment by cranepay** [comment]
fixed
9536611322ded14492ce4af778e432fbd851d364

**Comment by arminmacx** [comment]
No it still crash at launch the only version working is qt with boost right now
